Add common name parsing
cisco/mlspp pull request #177
Opened 2021-02-09 06:45 UTC by suhasHere

Cert parser returns certificate subject as hash output. Some applications might need access to the actual entry for verification purposes. This PR parses subject CN into string.

2021-02-09 07:12 UTC, dimarusyy commented on lib/hpke/src/certificate.cpp
> +    auto x509_name = X509_get_subject_name(cert);
auto *x509_name ?

2021-02-09 08:24 UTC, dimarusyy approved these changes

2021-02-10 19:14 UTC, bifurcation requested changes

2021-02-10 19:14 UTC, bifurcation commented on lib/hpke/src/certificate.cpp
> +struct ParsedX509Subject
It's pretty gross to just handle some specific fields out of the `Name` struct.  How about something like the following:

```C++
enum struct NameType : int {
  organization = NID_organizationName,
  organizational_unit = NID_organizationalUnitName,
  country = NID_countryName,
  state_or_province_name = NID_stateOrProvinceName,
  common_name = NID_commonName,
  serial_number = NID_serialNumber,
};

using ParsedName = std::map<NameType, std::string>;
```

That way your parsing code can just set `name[nid] = parsed_value`.

2021-02-10 19:14 UTC, bifurcation commented on lib/hpke/src/certificate.cpp
> +struct ParsedX509Subject
And for completeness, might as well do this for the issuer as well.

2021-02-10 19:14 UTC, bifurcation commented on lib/hpke/src/certificate.cpp
> +  static ParsedX509Subject parse_subject(X509* cert)
This should work on an `const X509_NAME*` so that you can use it with both subject and issuer.

2021-02-10 19:14 UTC, bifurcation commented on lib/hpke/src/certificate.cpp
> +  static ParsedX509Subject parse_subject(X509* cert)
Also, please add a comment here noting that this method does not implement fully general name parsing.  Duplicate entries are not supported; if they are present, the last one presented by OpenSSL is chosen.

2021-02-10 19:14 UTC, bifurcation commented on lib/hpke/src/certificate.cpp
> +Certificate::subject_common_name() const
Let's not destructure like this; instead just return the `ParsedName` representing the subject / issuer.

2021-02-12 18:56 UTC, bifurcation approved these changes

2021-02-12 18:56 UTC, merged